Add & remove
CarlosZ96/Tasks pull request #3
Opened 2023-05-20 00:29 UTC by CarlosZ96

An edit function is created to enable editing of the input with the task description and save this data in the list of objects, pressing enter changes the value and disables editing again until it is clicked.

2023-05-20 01:22 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @CarlosZ96 , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Your app is free of linters errors. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 01:22 UTC, ridwanediallo commented on src/task.js
> +    }
- [ ] Hello there, @CarlosZ96. You did an excellent job bringing your project to this point. However, there is a problem when we attempt to edit a task. When we click on a task to edit it, it is removed from local storage. Please ensure that this problem is resolved and that we are able to successfully edit a task. Not only will you meet the requirement, but your app will also provide a better user experience. :ok_hand: 😊

### Demo :point_down: 
[screen-capture.webm](https://github.com/CarlosZ96/Tasks/assets/89228743/8120e5fa-d6f2-41f6-82e5-d99ac4009939)

2023-07-17 19:05 UTC, Olamarx approved these changes
Hi @CarlosZ96, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>
## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- All methods in place ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-17 19:05 UTC, Olamarx commented on src/task.js
> +        }
- [OPTIONAL] I would recommend you work on the id, it does not rearrange after every delete and it is a requirement but the previous reviewer missed it that is why I made it optional.

2023-07-17 22:49 UTC, merged